name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/sharelocationblack24dp-1.png
    - assets/page-1/images/unsplash-bj24dhcge.png
    - assets/page-1/images/unsplash-j4ui2ch3oru.png
    - assets/page-1/images/trendingupblack24dp-1.png
    - assets/page-1/images/unsplash-c2yvzgwnxqc-bg.png
    - assets/page-1/images/unsplash-2vhtawp2um.png
    - assets/page-1/images/flat-color-icons-next.png
    - assets/page-1/images/unsplash-c2yvzgwnxqc-bg-wjW.png
    - assets/page-1/images/flat-color-icons-next-7RJ.png
    - assets/page-1/images/flat-color-icons-next-j9A.png
    - assets/page-1/images/flat-color-icons-google.png
    - assets/page-1/images/unsplash-eupkknip4me.png
    - assets/page-1/images/whh-circletwitter.png
    - assets/page-1/images/sharelocationblack24dp-1-eDe.png
    - assets/page-1/images/trendingupblack24dp-1-8Fi.png
    - assets/page-1/images/flat-color-icons-next-io2.png
    - assets/page-1/images/moq1-3-bg.png
    - assets/page-1/images/moq1-2-bg.png
    - assets/page-1/images/moq1-4-bg.png
    - assets/page-1/images/moq1-3-bg-cAc.png
    - assets/page-1/images/flat-color-icons-next-5bv.png
    - assets/page-1/images/moq1-3-bg-krU.png
    - assets/page-1/images/unsplash-2vhtawp2um-bg.png
    - assets/page-1/images/moq1-3-bg-ZUU.png
    - assets/page-1/images/moq1-3-bg-S7a.png
    - assets/page-1/images/moq1-3-bg-RmS.png
    - assets/page-1/images/trendingupblack24dp-1-9SQ.png
    - assets/page-1/images/flat-color-icons-next-YMn.png
    - assets/page-1/images/moq2-1-bg.png
    - assets/page-1/images/flat-color-icons-next-SyW.png
    - assets/page-1/images/flat-color-icons-next-7d2.png
    - assets/page-1/images/sharelocationblack24dp-1-KHA.png
    - assets/page-1/images/checkbox-empty.png
    - assets/page-1/images/flat-color-icons-next-Y4Y.png
    - assets/page-1/images/unsplash-c2yvzgwnxqc-bg-aBa.png
    - assets/page-1/images/flat-color-icons-google-u7n.png
    - assets/page-1/images/unsplash-c2yvzgwnxqc-bg-HoW.png
    - assets/page-1/images/flat-color-icons-next-XB6.png
    - assets/page-1/images/unsplash-eupkknip4me-bg.png
    - assets/page-1/images/ci-hamburger.png
    - assets/page-1/images/unsplash-asuspycziwo-bg.png
    - assets/page-1/images/unsplash-asuspycziwo-bg-TCC.png
    - assets/page-1/images/unsplash-asuspycziwo-bg-XEY.png
    - assets/page-1/images/unsplash-asuspycziwo-bg-nHW.png
    - assets/page-1/images/flat-color-icons-next-y92.png
    - assets/page-1/images/whh-circletwitter-4qn.png
    - assets/page-1/images/unsplash-j4ui2ch3oru-yRz.png
    - assets/page-1/images/trendingupblack24dp-1-mR2.png
    - assets/page-1/images/flat-color-icons-next-fQ4.png
    - assets/page-1/images/carbon-next-outline.png
    - assets/page-1/images/sharelocationblack24dp-1-Gqv.png
    - assets/page-1/images/unsplash-bj24dhcge-R8L.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
